import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/module/ui/navbar/NavBar";
import ThemeProvider from "@/provider/ThemeProvider";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Mi tienda",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body>
        <ThemeProvider>
          <Toaster />
          <NavBar />
          <main className="main">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
