import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import styles from "./layout.module.css";
import NavBar from "@/module/ui/navbar/NavBar";

export const metadata: Metadata = {
  title: "Mi tienda",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  //  const distinctCartItems = useCartStore((state) =>
  //   new Set(state.items.map((item) => item.id)).size
  // );
  return (
    <html lang="es">
      <body>
        <NavBar />
        <main className="main">{children}</main>
      </body>
    </html>
  );
}
